### PR TITLE
Added Cucumber scenarios to show how 'attach_file' works at this moment

### PR DESCRIPTION
**Pull request by elzenar**
This is the tests that I mentioned  in the issue #50  

As a person who creates tests using Cucumber I want to attach file to Allure report at any possible place.

```
  Variations how a file can be attached:
      by place of 'attach_file' code: [
        in a step of Scenario,
        in a step of Scenario Outline,
        in a step of Background,
        in hook 'Before',
        in hook 'After',
        in Around if to call 'attach_file' before block.call,
        in Around if to call 'attach_file' after block.call
      ]

      by using '--expand': [
        expand yes,
        expand no
      ]

      # This is an extra test case to check existing defect
      by attach_file's step position: [
        first step ,
        second step
      ]

```

### CODE REVIEW

**Comment by tk8817** [comment]
Great work @elzenar, I will review it this week.

@9ikhan can you please add Travis build permissions to this repo so we can get these tests running on every PR. I am not an admin so I cannot set this up for you.

**Comment by tk8817** [comment]
@baev is @9ikhan still working on this project? I cannot reach him and I would like to ensure we are still actively maintaining these bindings.

**Comment by 9ikhan** [comment]
@tk8817 - Very much working on it. I missed the mail notifications. I'll get it done.

**Comment by 9ikhan** [comment]
I have added the permissions in travis.

**Pull request merged**
