### PR TITLE
Bugfix: Fix scenario status if failure happens in before/after hook

### PR DESCRIPTION
**Pull request by tk8817**
This bugfix ensures that Allure correctly reports a scenario as failed in cases where the failure occurs during a before hook. Currently, allure-cucumber reports such a scenario as skipped (takes the status of the last step).

Note: @KorranForce contributed the portion regarding getting the exception from the before/after hooks.

### CODE REVIEW

**Comment by tk8817** [comment]
@KorranForce - FYI this is my contribution.

**Comment by tk8817** [comment]
@9ikhan can we also get this merged, its much better behaviour than exists today. We can work on getting the exception message captured in a different PR.

**Comment by tk8817** [comment]
@9ikhan, @KorranForce has solved the issue of getting the actual exception from Cucumber, it was not easy! So that means we have a full solution to this problem now. 

Please review the updated PR and lets try get this in ASAP.

**Comment by tk8817** [comment]
@9ikhan I can rebase and squash the commits once the other PR is merged.

**Comment by tk8817** [comment]
@9ikhan I have rebased & squashed this commit against the latest master, please review.

**Comment by tk8817** [comment]
@9ikhan are we going to take a look at this? it is quite important to fix.

**Comment by 9ikhan** [comment]
Sorry, I've not been able to look into this for a while. I'll try to close
this by weekend.

**Pull request merged**
