### PR TITLE
Add option to enable file attachments to cucumber scenarios

### PR DESCRIPTION
**Pull request by vgrigoruk**
Optional argument added to "AllureCucumber::DSL.attach_file" method, that allows you to control attachment target: step or scenario. Default behaviour remain the same (files are attached to steps).

### CODE REVIEW

**Comment by 9ikhan** [comment]
Hi

I assumed that files will always be attach to specific steps. Can you please tell me your use case ?

**Comment by vgrigoruk** [comment]
I have the following use case.
1. I'm using @After scenario hook to check if scenario has failed make a browser / mobile app screenshot (capybara-screenshot ruby gem).
2. Then I've implemented additional @After hook in my code, to attach screenshot from previous step to allure report. The issue is that in this setup a screenshot will be always attached to the last step in cucumber scenario (even if test has failed on one of previous steps, and the last step is marke as skipped).

Another reason: it will be just very nick if we can make attachments to both steps and scenarios (considering that this is already implemented in a project).

**Comment by 9ikhan** [comment]
@vgrigoruk - There are merge conflicts. Please merge the latest `master` branch into your branch and push the changes. I'll merge it then.

**Comment by vgrigoruk** [comment]
Done, please merge.

**Pull request merged**
